In [1]:
pwd


'C:\\Users\\Blazt\\Udemy python'

In [1]:
t= lambda var:var*3


In [2]:
t(3)

9

In [3]:
t(30)

90

In [9]:
import pandas as pd
import numpy as np

data = {
    'welcome': 'selamat datang',
    'id': [1,2,3,4],
    'nama': ['andi','budi','caca','arnold'],
    'job' : ['pns','programmer','waitress','designer'],
    'random' : pd.Series(np.arange(4)),
    'updated' : pd.Timestamp('20190220'),
    'range' : pd.date_range('20190220',periods=4)
}

data.values()

dict_values(['selamat datang', [1, 2, 3, 4], ['andi', 'budi', 'caca', 'arnold'], ['pns', 'programmer', 'waitress', 'designer'], 0    0
1    1
2    2
3    3
dtype: int32, Timestamp('2019-02-20 00:00:00'), DatetimeIndex(['2019-02-20', '2019-02-21', '2019-02-22', '2019-02-23'], dtype='datetime64[ns]', freq='D')])

In [15]:
x = [(1,2),(3,4),(5,6)]

for item in x:
    print(x)
    
for (a,b) in x:
    print(b)

[(1, 2), (3, 4), (5, 6)]
[(1, 2), (3, 4), (5, 6)]
[(1, 2), (3, 4), (5, 6)]
2
4
6


In [16]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [33]:
lst[3][1]

[100, 200, ['hello']]

In [44]:
def countdog(st):
    count = 0
    for word in st.lower().split():
        if word == 'dog':
            count += 1
    return count
    
countdog('dog alias asu dog dog dog')

4

In [43]:
list(filter(lambda word: word[0]=='s',seq))

4

In [2]:
import numpy as np

np.arange(2,13,1)
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.linspace(1,10,50) #rangenya , jumlahnya


array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [7]:
np.arange (1,10,1) #rangenya, stepnya

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.random.randint(1,10,10) #range, banyaknya

array([3, 6, 2, 8, 9, 6, 7, 4, 3, 7])

In [18]:
randomarray = np.random.randint(1,100,25)
randomarray 
randomarray.reshape(5,5) #hitung volumenya untuk mengecheck

array([[68,  3, 86, 83, 16],
       [33, 92, 24, 70, 47],
       [ 7, 88, 40, 40, 20],
       [99, 59, 23, 74, 23],
       [72, 77, 22, 50, 62]])

In [25]:
print(randomarray.max())
print('lokasinya pada urutan ke  = ', randomarray.argmax())
print('type array  = ', randomarray.dtype)


99
lokasinya pada urutan ke  =  15
type array  =  int32


In [10]:
array2d = np.array([[2,3,4],[3,4,2],[8,6,4]])
print(array2d)

[[2 3 4]
 [3 4 2]
 [8 6 4]]


In [8]:

print(array2d[:2,1:])

[[3 4]
 [4 2]]


In [9]:

print(array2d[:2]) #ambil semua kecuali kolom index ke 3 

[[2 3 4]
 [3 4 2]]


In [12]:

print(array2d[:,2: ])

[[4]
 [2]
 [4]]
